name: test_task_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_snack_bar: ^0.4.0
  animated_splash_screen: ^1.3.0
  auto_route: ^11.0.0
  chopper: ^8.4.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  modal_bottom_sheet: ^3.0.0
  reactive_forms: ^18.2.0
  reactive_forms_annotations: ^8.0.1
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  auto_route_generator: ^10.4.0
  package_rename: ^1.10.1
  chopper_generator: ^8.4.0
  equatable: ^2.0.7
  bloc: ^9.1.0
  async: ^2.13.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.13
  build_runner: ^2.10.4
  json_serializable: ^6.11.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/main_logo.png"

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    image: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  main_locale: ru

package_rename_config:
  android:
    app_name: "TTA"
 
  ios:
    app_name: "TTA"
